# Generated by Django 3.0.5 on 2020-05-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200502_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pubdate',
            field=models.DateField(auto_now=True),
        ),
    ]
